# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.13

# Mod Properties
mod_version=1.0.0
maven_group=com.example
archives_base_name=modid

# Dependencies
fabric_version=0.121.0+1.21.5
map_canvas_api_version=0.5.0+1.21.3
polymer_version=0.12.3+1.21.5
bil_version=1.2.4+1.21.5-rc1
sidebar_version=0.5.1+1.21.1
placeholder_version=2.6.2+1.21.5